//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pw_transactions
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public decimal amount { get; set; }
        public decimal balance { get; set; }
        public int usersID { get; set; }
        public string userName { get; set; }
    
        public virtual pw_users pw_users { get; set; }
    }
}
